# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sZhMEYIJbwpVKi7cdMPSVEYAul9LYXLq
"""

raw_data = """
-0.06738281,-0.08325195,0.976318336
-0.10546875,-0.08691406,0.9267578
-0.10571289,-0.07299805,0.939209
-0.119628904,-0.215576176,0.8413086
0.029785156,-0.04345703,0.94189452
-0.07373047,-0.024658204,1.0075684
0.0546875,0.01977539,0.9560547
0.026611328,-0.0234375,0.97753908
-0.004638672,-0.080566408,0.9970703
0.055908204,-0.053710936,1.0471192
0.0078125,-0.07714844,1.0073242
-0.15429688,-0.052734376,0.99365232
-0.15039062,-0.08691406,0.923584
-0.21142578,-0.2355957,0.813964836
-0.16210938,-0.183593744,0.7963867
-0.14428711,-0.2097168,0.7709961
0.10083008,-0.23339844,0.8129883
0.061035156,-0.2355957,0.68310544
0.1586914,-0.175048832,0.8913574
0.19335938,-0.09863281,0.9465332
0.20874024,-0.1237793,0.9008789
-0.043701172,-0.27075196,0.81274416
0.013427734,-0.06323242,0.871582032
0.15551758,-0.203125,0.84277348
0.057861328,-0.1237793,1.1154785
0.088378904,-0.40966796,0.9465332
0.07763672,-0.14501953,0.99731448
0.016113282,-0.14233398,1.0090332
0.072021484,-0.15478516,0.951416
0.05126953,0.030761718,1.0578613
-0.037353516,0.07299805,1.0029297
-0.02758789,-0.1274414,0.8522949
0.0041503908,0.099609376,1.0534668
-0.064453124,-0.1550293,0.88305668
0.0061035156,-0.08862305,0.9440918
0.07446289,-0.055908204,0.8847656
0.06933594,-0.0024414062,0.9177246
0.044189452,0.059814452,0.9458008
0.07055664,0.0539550768,0.985351536
0.0024414062,0.0715332,1.0334473
-0.011474609,0.02709961,0.9968262
0.02368164,-0.10595703,0.9238281
0.05102539,-0.045166016,0.9736328
0.10449219,0.048095704,0.986084
0.08959961,0.033203124,0.9746094
0.09448242,-0.029541016,0.9614258
0.07763672,0.061523436,0.99194332
-0.009765625,-0.042236328,0.998535136
-0.056884764,-0.036376952,1.0019531
0.0214843736,-0.045898436,0.9975586
0.08300781,-0.045654296,0.9416504
0.022705078,0.009765625,0.9812012
0.05834961,-0.115478516,0.91015624
0.1586914,0.009521484,0.9729004
0.13232422,-0.09472656,0.93310544
0.1508789,0.018310546,0.9831543
0.022949218,-0.13061524,0.9416504
0.036376952,-0.18725586,0.873535168
-0.00048828124,-0.13085938,0.8781738
0.019042968,-0.14990234,0.970214864
0.06738281,-0.215576176,0.9003906
0.076171868,-0.14257812,0.8857422
0.084228516,-0.091308592,0.93115232
0.08203125,-0.1262207,0.9157715
0.068115232,-0.03491211,0.9934082
-0.060546876,-0.16015625,0.90625
-0.10546875,-0.09741211,0.9133301
-0.03125,-0.215332032,0.9831543
-0.05493164,-0.12353516,0.98291016
-0.060791016,-0.28393556,0.93774416
-0.0017089844,-0.049560548,0.94433592
-0.09399414,-0.24267578,0.934082064
-0.07885742,-0.25634766,0.87060544
-0.1184082,-0.119628904,0.9123535
-0.091308592,-0.26098632,0.8835449
0.047851564,-0.042236328,0.9748535
0.02368164,-0.12915039,0.9411621
0.011230469,-0.10205078,0.958251968
0.045898436,-0.11401367,0.938964864
0.2487793,0.0690918,1.0776367
0.07519531,-0.14819336,0.94873048
0.045654296,-0.13964844,0.91430664
0.1184082,-0.07714844,1.0192871
0.11669922,-0.059326172,0.9260254
0.08300781,-0.060302736,0.9375
0.057373048,-0.15527344,0.9111328
0.0017089844,-0.1616211,0.8774414
-0.03515625,-0.15014648,0.94750976
0.0146484368,-0.087646488,0.97998052
0.0026855468,-0.24902344,0.858398464
-0.009765625,-0.19458008,0.8510742
0.063964844,-0.2163086,0.8835449
0.12719726,-0.07397461,1.012207
0.09667969,-0.07763672,0.9814453
0.024169922,-0.27416992,0.8105469
0.246337884,0.2890625,1.1096192
0.11303711,-0.099121096,0.8654785
0.0769043,-0.12426758,0.894531264
0.2319336,-0.01928711,0.98168948
0.16674804,-0.343505868,0.80029292
"""

import matplotlib.pyplot as plt

x_val, y_val, z_val = [], [], []

# แปลงข้อมูลตัวอักษรให้กลายเป็น Array ตัวเลข
for line in raw_data.strip().split("\n"):
    if line:
        parts = line.split(",")
        x_val.append(float(parts[0]))
        y_val.append(float(parts[1]))
        z_val.append(float(parts[2]))

# พล็อตด้วย Matplotlib บน Google Colab
plt.figure(figsize=(12, 6))
plt.plot(x_val, label="X-axis (Left/Right)", color="red", linewidth=1.5)
plt.plot(y_val, label="Y-axis (Forward/Backward)", color="green", linewidth=1.5)
plt.plot(z_val, label="Z-axis (Up/Down)", color="blue", linewidth=1.5)

plt.title("GY-521 Accelerometer Data Analysis", fontsize=14, fontweight='bold')
plt.xlabel("Data Points (Samples)", fontsize=12)
plt.ylabel("Acceleration (g)", fontsize=12)
plt.grid(True, linestyle="--", alpha=0.6)
plt.legend(loc="upper right")

# แสดงผลกราฟบนหน้าจอ Colab ทันที
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# 1. Paste your raw data string from Thonny here

# 2. Extract and parse data into lists
x_val, y_val, z_val = [], [], []
for line in raw_data.strip().split("\n"):
    if line and not line.startswith("-"): # Skip header lines if any
        parts = line.split(",")
        if len(parts) == 3:
            x_val.append(float(parts[0]))
            y_val.append(float(parts[1]))
            z_val.append(float(parts[2]))

# Convert to Numpy Arrays for mathematical operations
x_arr = np.array(x_val)
y_arr = np.array(y_val)
z_arr = np.array(z_val)

# CRUCIAL: Remove the DC component (gravity/constant offsets)
# Subtracting the mean prevents a massive, blinding spike at 0 Hz on your graph
x_arr = x_arr - np.mean(x_arr)
y_arr = y_arr - np.mean(y_arr)
z_arr = z_arr - np.mean(z_arr)

# 3. FFT Configuration Parameters
# In your ESP32 code, time.sleep(0.05) creates a delay of 0.05 seconds.
# This means your Sampling Frequency (fs) = 1 / 0.05 = 20 Hz.
fs = 20           # Sampling rate in Hz (Samples per second)
N = len(x_arr)    # Total number of data samples collected

# Compute the Fast Fourier Transform (FFT)
fft_x = np.fft.fft(x_arr)
fft_y = np.fft.fft(y_arr)
fft_z = np.fft.fft(z_arr)

# Generate the frequency X-axis matching the samples
frequencies = np.fft.fftfreq(N, d=1/fs)

# FFT results are symmetrical. We only care about the positive half (Single-Sided Spectrum)
half_N = N // 2
frequencies = frequencies[:half_N]

# Calculate the magnitude (amplitude) of the frequencies and normalize them
amplitude_x = np.abs(fft_x[:half_N]) * 2 / N
amplitude_y = np.abs(fft_y[:half_N]) * 2 / N
amplitude_z = np.abs(fft_z[:half_N]) * 2 / N

# 4. Plot the Fourier Transform Graph
plt.figure(figsize=(12, 6))

plt.plot(frequencies, amplitude_x, label="X-axis Frequency", color="red", linewidth=1.5)
plt.plot(frequencies, amplitude_y, label="Y-axis Frequency", color="green", linewidth=1.5)
plt.plot(frequencies, amplitude_z, label="Z-axis Frequency", color="blue", linewidth=1.5)

# Graph styling
plt.title("Frequency Domain Spectrum (Fourier Transform)", fontsize=14, fontweight='bold')
plt.xlabel("Frequency (Hz)", fontsize=12)
plt.ylabel("Amplitude / Strength", fontsize=12)
plt.grid(True, linestyle="--", alpha=0.5)
plt.legend()

# Limit the X-axis up to the Nyquist Frequency (fs / 2 = 10 Hz)
plt.xlim(0, fs / 2)

plt.show()

